Add support for Execution Environments
sabre1041/sigstore-ansible pull request #2
Opened 2023-02-24 15:33 UTC by mayaCostantini

- [ ] Add support for Execution Environments
- [ ] Add a `.gitignore`
- [ ] Increase timeout for connecting to Keycloak and Rekor

2023-02-24 18:44 UTC, sabre1041 requested changes
A couple of comments

2023-02-24 18:44 UTC, sabre1041 commented on roles/sigstore_scaffolding/tasks/podman/tuf.yml
> -  retries: 5
Do we want to make these and the others configurable as different operating environment will have different failure rates (time to pull down the image etc)

2023-02-24 18:44 UTC, sabre1041 commented on README.md
> +ansible-runner run -i inventory -p playbooks/install.yml --container-image=my_ee .
We should be using [ansible-navigator](https://ansible-navigator.readthedocs.io) instead of calling `ansible-runner` directly

2023-02-27 10:06 UTC, mayaCostantini commented
Thank you for the review @sabre1041, adjustements were made in https://github.com/sabre1041/sigstore-ansible/pull/2/commits/b258850ade584b66cfd30347cf3e9d1aea30a71b.

2023-03-25 18:59 UTC, sabre1041 approved these changes
LGTM

2023-03-25 18:59 UTC, merged